apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  destination:
    namespace: ci-cd
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: jenkins
    repoURL: https://ArtegaAS.github.io/jenkins-helm
    targetRevision: 0.1.0
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
    - CreateNamespace=true
status:
  controllerNamespace: argocd
  health:
    status: Healthy
  resourceHealthSource: appTree
  resources:
  - kind: ConfigMap
    name: basic-security
    namespace: ci-cd
    status: Synced
    version: v1
  - kind: ConfigMap
    name: jenkins-config
    namespace: ci-cd
    status: Synced
    version: v1
  - kind: Namespace
    name: ci-cd
    status: Synced
    version: v1
  - kind: Secret
    name: jenkins-secret
    namespace: ci-cd
    status: Synced
    version: v1
  - kind: Service
    name: jenkins
    namespace: ci-cd
    status: Synced
    version: v1
  - group: apps
    kind: Deployment
    name: jenkins
    namespace: ci-cd
    status: Synced
    version: v1
  - group: autoscaling
    kind: HorizontalPodAutoscaler
    name: jenkins
    namespace: ci-cd
    status: Synced
    version: v2
  - group: networking.k8s.io
    kind: Ingress
    name: ingress-jenkins
    namespace: ci-cd
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: jenkins
    status: Synced
    version: v1
  sourceHydrator: {}
  sourceType: Helm
  summary:
    externalURLs:
    - http://jenkins.k8s-1.sa/
    images:
    - jfrog.it-academy.by/public/jenkins-ci:svavchinnik_33
  sync:
    comparedTo:
      destination:
        namespace: ci-cd
        server: https://kubernetes.default.svc
      source:
        chart: jenkins
        repoURL: https://ArtegaAS.github.io/jenkins-helm
        targetRevision: 0.1.0
    revision: 0.1.0
    status: Synced
