apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2025-11-24T11:30:26Z"
  generation: 15
  name: nginx-emp
  namespace: argocd
  resourceVersion: "3403450"
  uid: 10ce086b-e36a-464e-b921-6bbee1bdeb42
spec:
  destination:
    namespace: ci-cd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./apps/
    repoURL: https://github.com/ArtegaAS/argo-flux-33-25.git
    targetRevision: main
  syncPolicy:
    automated:
      enabled: true
status:
  controllerNamespace: argocd
  health:
    lastTransitionTime: "2025-11-24T11:31:16Z"
    status: Healthy
  history:
  - deployStartedAt: "2025-11-24T11:30:27Z"
    deployedAt: "2025-11-24T11:30:27Z"
    id: 0
    initiatedBy:
      automated: true
    revision: eaa4db6e6b2759fd3c067f94a376d348de762f6b
    source:
      path: ./apps/
      repoURL: https://github.com/ArtegaAS/argo-flux-33-25.git
      targetRevision: main
  operationState:
    finishedAt: "2025-11-24T11:30:27Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        automated: true
      retry:
        limit: 5
      sync:
        revision: eaa4db6e6b2759fd3c067f94a376d348de762f6b
        source:
          path: ./apps/
          repoURL: https://github.com/ArtegaAS/argo-flux-33-25.git
          targetRevision: main
    phase: Succeeded
    startedAt: "2025-11-24T11:30:27Z"
    syncResult:
      resources:
      - group: ""
        hookPhase: Running
        kind: Secret
        message: secret/nginx-passwords created
        name: nginx-passwords
        namespace: default
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: ConfigMap
        message: configmap/nginx-index created
        name: nginx-index
        namespace: default
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: ConfigMap
        message: configmap/nginx-conf created
        name: nginx-conf
        namespace: default
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/nginx-service created
        name: nginx-service
        namespace: default
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        images:
        - nginx:1.25
        - php:8.2-fpm
        kind: Deployment
        message: deployment.apps/nginx-deployment created
        name: nginx-deployment
        namespace: default
        status: Synced
        syncPhase: Sync
        version: v1
      - group: networking.k8s.io
        hookPhase: Running
        kind: Ingress
        message: ingress.networking.k8s.io/nginx-ingress created
        name: nginx-ingress
        namespace: default
        status: Synced
        syncPhase: Sync
        version: v1
      revision: eaa4db6e6b2759fd3c067f94a376d348de762f6b
      source:
        path: ./apps/
        repoURL: https://github.com/ArtegaAS/argo-flux-33-25.git
        targetRevision: main
  reconciledAt: "2025-11-24T11:37:32Z"
  resourceHealthSource: appTree
  resources:
  - kind: ConfigMap
    name: nginx-conf
    namespace: default
    status: Synced
    version: v1
  - kind: ConfigMap
    name: nginx-index
    namespace: default
    status: Synced
    version: v1
  - kind: Secret
    name: nginx-passwords
    namespace: default
    status: Synced
    version: v1
  - kind: Service
    name: nginx-service
    namespace: default
    status: Synced
    version: v1
  - group: apps
    kind: Deployment
    name: nginx-deployment
    namespace: default
    status: Synced
    version: v1
  - group: networking.k8s.io
    kind: Ingress
    name: nginx-ingress
    namespace: default
    status: Synced
    version: v1
  sourceHydrator: {}
  sourceType: Directory
  summary:
    externalURLs:
    - http://nginx-test.k8s-1.sa/
    images:
    - nginx:1.25
    - php:8.2-fpm
  sync:
    comparedTo:
      destination:
        namespace: ci-cd
        server: https://kubernetes.default.svc
      source:
        path: ./apps/
        repoURL: https://github.com/ArtegaAS/argo-flux-33-25.git
        targetRevision: main
    revision: eaa4db6e6b2759fd3c067f94a376d348de762f6b
    status: Synced
