apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-emp
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet:
        tlas:
        - name: ""
          value: ""
    path: ./apps/
    repoURL: https://github.com/ArtegaAS/argo-flux-33-25.git
    targetRevision: main
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
    - CreateNamespace=true
status:
  controllerNamespace: argocd
  health:
    status: Healthy
  resourceHealthSource: appTree
  resources:
  - kind: ConfigMap
    name: nginx-conf
    namespace: default
    status: Synced
    version: v1
  - kind: ConfigMap
    name: nginx-index
    namespace: default
    status: Synced
    version: v1
  - kind: Secret
    name: nginx-passwords
    namespace: default
    status: Synced
    version: v1
  - kind: Service
    name: nginx-service
    namespace: default
    status: Synced
    version: v1
  - group: apps
    kind: Deployment
    name: nginx-deployment
    namespace: default
    status: Synced
    version: v1
  - group: networking.k8s.io
    kind: Ingress
    name: nginx-ingress
    namespace: default
    status: Synced
    version: v1
  sourceHydrator: {}
  sourceType: Directory
  summary:
    externalURLs:
    - http://nginx-test.k8s-1.sa/
    images:
    - nginx:1.25
    - php:8.2-fpm
  sync:
    comparedTo:
      destination:
        namespace: default
        server: https://kubernetes.default.svc
      source:
        directory:
          jsonnet:
            tlas:
            - name: ""
              value: ""
        path: ./apps/
        repoURL: https://github.com/ArtegaAS/argo-flux-33-25.git
        targetRevision: main
    revision: 9ab1442e5107895877251537dc6f895ae36dd538
    status: Synced
