apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealsecret
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.17.9
  syncPolicy:
    automated:
      enabled: true
status:
  controllerNamespace: argocd
  health:
    status: Healthy
  resourceHealthSource: appTree
  resources:
  - kind: Service
    name: sealsecret-sealed-secrets
    namespace: kube-system
    status: Synced
    version: v1
  - kind: Service
    name: sealsecret-sealed-secrets-metrics
    namespace: kube-system
    status: Synced
    version: v1
  - kind: ServiceAccount
    name: sealsecret-sealed-secrets
    namespace: kube-system
    status: Synced
    version: v1
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: sealedsecrets.bitnami.com
    status: Synced
    version: v1
  - group: apps
    kind: Deployment
    name: sealsecret-sealed-secrets
    namespace: kube-system
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: secrets-unsealer
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: sealsecret-sealed-secrets
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: Role
    name: sealsecret-sealed-secrets-key-admin
    namespace: kube-system
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: Role
    name: sealsecret-sealed-secrets-service-proxier
    namespace: kube-system
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
    name: sealsecret-sealed-secrets-key-admin
    namespace: kube-system
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
    name: sealsecret-sealed-secrets-service-proxier
    namespace: kube-system
    status: Synced
    version: v1
  sourceHydrator: {}
  sourceType: Helm
  summary:
    images:
    - docker.io/bitnami/sealed-secrets-controller:0.33.1
  sync:
    comparedTo:
      destination:
        namespace: kube-system
        server: https://kubernetes.default.svc
      source:
        chart: sealed-secrets
        repoURL: https://bitnami-labs.github.io/sealed-secrets
        targetRevision: 2.17.9
    revision: 2.17.9
    status: Synced
